version: "2.20.2"

services:
  patientdb:
    container_name: patientdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: patientdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config

  configserver:
    image: siferga/configserver
    container_name: configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    #    extends:
    #      file: common-config.yml
    #      service: microservise-base-config
    networks:
      - Healthcare-network

  eurekaserver:
    image: siferga/eurekaserver
    container_name: eurekaserver
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: ""
    networks:
      - Healthcare-network

  patient:
    image: siferga/
    container_name:
    ports:
      - "807:807"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    #    extends:
    #      file: common-config.yml
    #      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    networks:
      - Healthcare-network

networks:
  Healthcare-network:
