server:
  port:
    9000
#Config General
spring:
  application:
    name: patient

  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/patientdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:configserver:https://localhost:8071/
#Configuration EUREKA CLIENT
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka

#Configuration de l'affichage des info
info:
  app:
    name: "Patient"
    description: "Healtcare app"
    version: "1.0.0"
