spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
# will be used into the docker-compose to pass the healthcheck step
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
#  metrics:
#    tags:
#      application: ${spring.application.name}
#
#logging:
#  pattern:
#    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
